# Generated by Django 5.0.3 on 2024-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterGDSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('education', models.CharField(choices=[('Graduate', 'Graduate'), ('Non-Graduate', 'Non-Graduate')], max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
