# Generated by Django 5.0.3 on 2024-03-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdsc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registergdsc',
            options={'ordering': ['id'], 'verbose_name': 'GDSC Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
