# Generated by Django 5.0.3 on 2024-03-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdsc_app', '0002_alter_registergdsc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registergdsc',
            options={'ordering': ['created_at'], 'verbose_name': 'GDSC Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AddField(
            model_name='registergdsc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registergdsc',
            name='school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
